### ISSUE TITLE
10.12 Sierra - "Can't find Principal from AD: 'NoneType'" 

### ISSUE THREAD

**Issue by danshaw** [pmbuko/KerbMinder#15]
Just upgraded to Sierra to try Kerbminder and when I try to run it manually from terminal on a bound Mac I am seeing the following error.

$ sudo python Kerbminder.py
Can't find Principal from AD: 'NoneType' object has no attribute 'group'. Exiting.

I'll continue to do some more testing, but not sure if this is a Sierra issue or not. Works fine on 10.10 & 10.11.

**Comment by ftiff** [comment]
Hi danshaw, 
This is a bug that is fixed in 1.4. Could you have a go? 
https://github.com/pmbuko/KerbMinder/releases/tag/v1.4

Thanks!
François

**Comment by danshaw** [comment]
Hey Francois - You sent me a copy of 1.4 a couple months ago. So I am using that one. I just installed the version you posted here and I am also getting the same error. I might spin up another 10.12 VM and see if that works.

**Comment by ftiff** [comment]
can you send me the output of this command:
`dscl /Search read /Users/[your user] AuthenticationAuthority`?

@ftiff on slack if you don't want to share publicly

**Comment by ftiff** [comment]
@danshaw was using sudo to launch Kerbminder.
Added a check to forbid this https://github.com/pmbuko/KerbMinder/commit/356bcc2ff54b5f57ee1b75f71c1ffe54ad36c136

Thanks a lot for filling an issue!
